before_install:
  - sudo apt-get install virtualbox
  - sudo apt-get install vagrant
bundler_args: ''
script:
  - vagrant box add hashicorp/precise32
  - vagrant up
  - vagrant halt
  - vagrant destroy
